name: freshbasket
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  convex_bottom_bar: ^3.2.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_neumorphic_plus: ^3.4.0
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_icon.png
    - assets/login_image.png
    - assets/animations/loading.json
    - assets/animations/delete.json
    - assets/animations/logout.json
    - assets/animations/empty_cart.json
    - assets/images/default_avatar.png
    - assets/animations/success.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
